<?php

namespace Paytic\Omnipay\Mobilpay\Message\Soap\Payment;

use Paytic\Omnipay\Mobilpay\Message\Soap\SoapResponse;

/**
 * Class DoPayTResponse
 * @package Paytic\Omnipay\Mobilpay\Message\Soap\Payment
 */
class DoPayTResponse extends SoapResponse
{
    public function isSuccessful()
    {
        parent::isSuccessful();
    }

    public function getCode()
    {
        if (isset($this->data->doPayTResult->errors->code)) {
            return $this->data->doPayTResult->errors->code;
        }
        return parent::getCode(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritDoc
     */
    public function getTransactionId()
    {
        if (isset($this->data->doPayTResult->order->id)) {
            return $this->data->doPayTResult->order->id;
        }
        return parent::getTransactionId();
    }

    /**
     * @inheritDoc
     */
    public function getTransactionReference()
    {
        if (isset($this->data->doPayTResult->transaction->id)) {
            return $this->data->doPayTResult->transaction->id;
        }
        return parent::getTransactionReference();
    }
}
